-- Migration: 20260512110000_seed_name_anchors_to_98.sql
-- Purpose: Replace the 32 existing rows in public.name_anchors with the 98
--          canonical rows from assets/content/name_anchors.json (Plan 4 —
--          2026-05-12 — backfill from 32 to 98 by dropping the 3 non-canonical
--          anchors al-qarib, ar-rabb, al-jamil and authoring 69 new entries).
--
-- Schema source: supabase/migrations/20260407000000_initial_schema.sql lines 120-127
--   create table public.name_anchors (
--     name_key text primary key,
--     name text not null,
--     arabic text not null,
--     anchor text not null,
--     detail text not null,
--     created_at timestamptz not null default now()
--   );
--
-- RLS: anon read policy lives in 20260409190000_public_catalog_anon_read.sql
-- and is preserved. We do not drop or alter the table — only the row data.
--
-- Note: TRUNCATE removes all 32 existing rows including the 3 non-canonical
-- anchors (al-qarib, ar-rabb, al-jamil) that Plan 4 deprecated.
--
-- Idempotency: TRUNCATE before INSERT, all inside a single transaction.
--
-- Apostrophes and Arabic text are wrapped in $sk$...$sk$ dollar-quoted strings
-- so no escaping is required.

begin;

truncate table public.name_anchors;

insert into public.name_anchors (name_key, name, arabic, anchor, detail, created_at) values
  ($sk$ad-darr$sk$, $sk$Ad-Darr$sk$, $sk$الضَّارُّ$sk$, $sk$Even what causes you pain is under His authority.$sk$, $sk$Ad-Darr is the One in whose hand difficulty resides. Nothing harms you outside His permission, which means no hardship is meaningless. He uses even pain to shape what is being made of you.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-adl$sk$, $sk$Al-Adl$sk$, $sk$الْعَدْلُ$sk$, $sk$His justice is exact — and woven with mercy.$sk$, $sk$Al-Adl is the Just. He gives every soul its precise due, not a particle more or less. And His justice is not cold: it is held inside a mercy that often outweighs what is strictly deserved.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-afuw$sk$, $sk$Al-'Afuw$sk$, $sk$الْعَفُوُ$sk$, $sk$His forgiveness erases — it doesn't just cover.$sk$, $sk$Al-'Afuw goes further than forgiveness: it means to completely wipe away, as if it never happened. Ask for it often. It is what the Prophet ﷺ taught us to seek on Laylatul Qadr.$sk$, $sk$2026-04-07T18:33:14.151294+00:00$sk$::timestamptz),
  ($sk$al-ahad$sk$, $sk$Al-Ahad$sk$, $sk$الْأَحَدُ$sk$, $sk$He is unique — there is nothing else like Him.$sk$, $sk$Al-Ahad is the Unique. Surat Al-Ikhlas opens with this Name. He has no partner, no equal, no comparison. The longing in you that no created thing can satisfy is a longing for the One who is utterly unique.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-akhir$sk$, $sk$Al-Akhir$sk$, $sk$الْآخِرُ$sk$, $sk$He will be there after everything ends.$sk$, $sk$Al-Akhir is the Last. Every relationship, every season of your life will one day end — except this one. He remains when the world does not. He is the constant on either side of your existence.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-aleem$sk$, $sk$Al-Aleem$sk$, $sk$الْعَلِيمُ$sk$, $sk$He knows what you cannot put into words.$sk$, $sk$Al-Aleem is the All-Knowing — His knowledge precedes your own awareness of yourself. When you can't name what is wrong, He already does, and He is gentle with what He finds.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-ali$sk$, $sk$Al-'Ali$sk$, $sk$الْعَلِيُّ$sk$, $sk$He sees your situation from above — all of it.$sk$, $sk$Al-'Ali is the Most High. His perspective encompasses what you cannot see from where you stand. Trust that He sees the full picture when you can only see a fragment.$sk$, $sk$2026-04-07T18:33:44.135017+00:00$sk$::timestamptz),
  ($sk$al-awwal$sk$, $sk$Al-Awwal$sk$, $sk$الْأَوَّلُ$sk$, $sk$He was there before anything you know.$sk$, $sk$Al-Awwal is the First — preceding all of creation, all of your story, all of time itself. Before you ever existed, He knew you. You are not a recent thought in His mind; you are an ancient one.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-azeem$sk$, $sk$Al-Azeem$sk$, $sk$الْعَظِيمُ$sk$, $sk$He is greater than the thing that is overwhelming you.$sk$, $sk$Al-Azeem is the Magnificent — the One whose greatness dwarfs everything else. The trial that feels enormous to you is small in His sight. He is bigger than your biggest worry.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-azeez$sk$, $sk$Al-Azeez$sk$, $sk$الْعَزِيزُ$sk$, $sk$He cannot be overcome — and neither can what He holds.$sk$, $sk$Al-Azeez is the Almighty, the Honored. Nothing in creation can overpower Him, and what He chooses to protect is protected. When you feel small or outmatched, remember whose strength is behind you.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-badi$sk$, $sk$Al-Badi$sk$, $sk$الْبَدِيعُ$sk$, $sk$He creates beauty that has no precedent.$sk$, $sk$Al-Badi is the Originator of new wonder — the One who brings into being things never seen before. The unique pattern of your life, the originality of your story, is His signature. He does not repeat Himself.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-baith$sk$, $sk$Al-Baith$sk$, $sk$الْبَاعِثُ$sk$, $sk$He raises what has died — including in you.$sk$, $sk$Al-Baith is the Resurrector — the One who brings the dead back to life on the Day of Judgement, and who can bring dead parts of a heart back to life now. What feels finished may not be.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-baqi$sk$, $sk$Al-Baqi$sk$, $sk$الْبَاقِي$sk$, $sk$When everything else fades, He remains.$sk$, $sk$Al-Baqi is the Everlasting — the One who is not subject to time or change. The relationships and seasons that will not last are pointing your heart toward the One who will. He is the lasting thing.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-bari$sk$, $sk$Al-Bari$sk$, $sk$الْبَارِئُ$sk$, $sk$He brings into being what did not exist before.$sk$, $sk$Al-Bari is the Originator who fashions things from nothing. The situation you cannot see a way through — He can bring forth a solution that has no precedent in your life. He is not limited to what already exists.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-barr$sk$, $sk$Al-Barr$sk$, $sk$الْبَرُّ$sk$, $sk$His kindness toward you is constant.$sk$, $sk$Al-Barr is the Source of Goodness — the One whose dealings with His servants are always kind. Even what looks harsh in your life is being administered by the Kindest One. Trust the source.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-basir$sk$, $sk$Al-Basir$sk$, $sk$الْبَصِيرُ$sk$, $sk$He sees everything others overlook in you.$sk$, $sk$Al-Basir is the All-Seeing. No effort you make, no hidden sacrifice, no quiet struggle goes unseen by Him. He witnesses what no one else does.$sk$, $sk$2026-04-07T18:33:44.135017+00:00$sk$::timestamptz),
  ($sk$al-basit$sk$, $sk$Al-Basit$sk$, $sk$الْبَاسِطُ$sk$, $sk$He widens what felt narrow.$sk$, $sk$Al-Basit is the Expander — the One who opens up rizq, opportunity, and the heart itself. After every contraction comes an expansion in His timing. The walls closing in are not the last word.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-batin$sk$, $sk$Al-Batin$sk$, $sk$الْبَاطِنُ$sk$, $sk$He is closer than your inner thoughts.$sk$, $sk$Al-Batin is the Hidden — not because He is far, but because He is closer than any outward thing. He is inside the heart, beneath the thoughts, present in the silence underneath your speech.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-fattah$sk$, $sk$Al-Fattah$sk$, $sk$الْفَتَّاحُ$sk$, $sk$Doors will open that you cannot open yourself.$sk$, $sk$Al-Fattah is the Opener of all things. No door is permanently shut to the one who returns to Him. The breakthrough you are waiting for is in His hands.$sk$, $sk$2026-04-07T18:33:14.151294+00:00$sk$::timestamptz),
  ($sk$al-ghaffar$sk$, $sk$Al-Ghaffar$sk$, $sk$الْغَفَّارُ$sk$, $sk$You are not defined by your worst moments.$sk$, $sk$Al-Ghaffar means the One who forgives repeatedly, without limit. The same sin brought back with a sincere heart is forgiven again. He does not keep a tally against you.$sk$, $sk$2026-04-07T18:33:14.151294+00:00$sk$::timestamptz),
  ($sk$al-ghafur$sk$, $sk$Al-Ghafur$sk$, $sk$الْغَفُورُ$sk$, $sk$His forgiveness covers what no one else can see.$sk$, $sk$Al-Ghafur is the Forgiving — the One who veils sin and pardons it. Where Al-Ghaffar emphasizes repeated forgiveness, Al-Ghafur emphasizes its completeness. What He forgives, He conceals.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-ghaniyy$sk$, $sk$Al-Ghaniyy$sk$, $sk$الْغَنِيُّ$sk$, $sk$He does not need anything from you — and yet He wants you.$sk$, $sk$Al-Ghaniyy is the Self-Sufficient. He has no need for your worship or attention; it is you who benefit from giving them. Knowing this frees your relationship with Him from any sense of transaction.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-hadi$sk$, $sk$Al-Hadi$sk$, $sk$الْهَادِي$sk$, $sk$You will be guided to where you need to be.$sk$, $sk$Al-Hadi is the Guide — the One who places clarity in hearts that ask for it. If you feel lost, ask Him directly: "Guide me." He answers that prayer.$sk$, $sk$2026-04-07T18:33:14.151294+00:00$sk$::timestamptz),
  ($sk$al-hafeez$sk$, $sk$Al-Hafeez$sk$, $sk$الْحَفِيظُ$sk$, $sk$He guards what you cannot protect yourself.$sk$, $sk$Al-Hafeez is the Preserver — the One who keeps safe what is entrusted to Him. Your faith, your loved ones, your wellbeing — when you place them in His care, He guards them with a vigilance you could never match.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-hakam$sk$, $sk$Al-Hakam$sk$, $sk$الْحَكَمُ$sk$, $sk$He is the Judge who will set every wrong right.$sk$, $sk$Al-Hakam is the ultimate Arbiter. Every injustice you have witnessed or suffered will be brought before Him, and He will judge with perfect knowledge. Nothing escapes His court.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-hakim$sk$, $sk$Al-Hakim$sk$, $sk$الْحَكِيمُ$sk$, $sk$Nothing in your life is wasted.$sk$, $sk$Al-Hakim means every decree has been placed with perfect wisdom. The things that make no sense to you now are woven with a purpose that will one day be clear.$sk$, $sk$2026-04-07T18:33:14.151294+00:00$sk$::timestamptz),
  ($sk$al-haleem$sk$, $sk$Al-Haleem$sk$, $sk$الْحَلِيمُ$sk$, $sk$He is patient with you in a way no one else is.$sk$, $sk$Al-Haleem is the Forbearing — slow to respond to wrong, quick to give space. Where a human would react, He gives you room to return. Your repeated mistakes have not exhausted His patience.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-hameed$sk$, $sk$Al-Hameed$sk$, $sk$الْحَمِيدُ$sk$, $sk$Every praise eventually points back to Him.$sk$, $sk$Al-Hameed is the Praiseworthy — the One who is worthy of all praise in every situation. Even the praise you give to people for their goodness ultimately traces back to the One who gave them that goodness.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-haqq$sk$, $sk$Al-Haqq$sk$, $sk$الْحَقُّ$sk$, $sk$He is the one Reality everything else points to.$sk$, $sk$Al-Haqq is the Truth — not merely truthful, but Truth itself. Every fleeting thing in this world has its source in Him. The disappointments of unreal things are signposts pointing toward the One who is real.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-haseeb$sk$, $sk$Al-Haseeb$sk$, $sk$الْحَسِيبُ$sk$, $sk$He accounts for every kindness you have ever offered.$sk$, $sk$Al-Haseeb is the Reckoner — the One who keeps the precise record. Every quiet good deed, every effort no one acknowledged, every small mercy you extended — He has counted it, and it will be returned to you.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-hayy$sk$, $sk$Al-Hayy$sk$, $sk$الْحَيُّ$sk$, $sk$He is alive in a way nothing else is.$sk$, $sk$Al-Hayy is the Ever-Living — life itself, not a thing that has life. When you feel emptied or numb, the One who is fully alive is the source you draw from. Ya Hayyu Ya Qayyum, the Prophet ﷺ would call out in difficulty.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-jabbar$sk$, $sk$Al-Jabbar$sk$, $sk$الْجَبَّارُ$sk$, $sk$He mends what has been broken in you.$sk$, $sk$Al-Jabbar comes from the root that means both to compel and to set a broken bone. He is the One who sets right what has been fractured — in circumstance, in heart, in body. He restores.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-jaleel$sk$, $sk$Al-Jaleel$sk$, $sk$الْجَلِيلُ$sk$, $sk$His majesty is a refuge, not a distance.$sk$, $sk$Al-Jaleel is the Majestic — the One whose grandeur inspires awe. But His majesty is the kind that draws you in, not pushes you away. The greater He is, the more profound it is that He attends to you.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-jami$sk$, $sk$Al-Jami$sk$, $sk$الْجَامِعُ$sk$, $sk$He will gather what has been scattered.$sk$, $sk$Al-Jami is the Gatherer — the One who will assemble all of humanity on the Day of Judgement, and who reunites what life has separated. The losses that scattered your heart will not stay scattered forever.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-kabeer$sk$, $sk$Al-Kabeer$sk$, $sk$الْكَبِيرُ$sk$, $sk$Nothing in your life is too big for Him.$sk$, $sk$Al-Kabeer is the Greatest — greater than any title, status, or power. The thing you cannot imagine getting through is a small thing in His sight. He has greatness to spare for whatever you bring Him.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-karim$sk$, $sk$Al-Karim$sk$, $sk$الْكَرِيمُ$sk$, $sk$He gives generously, without you having to deserve it.$sk$, $sk$Al-Karim is the Generous One who gives before you even ask, and gives more than you expected. His generosity is not proportional to your worthiness.$sk$, $sk$2026-04-07T18:33:44.135017+00:00$sk$::timestamptz),
  ($sk$al-khabir$sk$, $sk$Al-Khabir$sk$, $sk$الْخَبِيرُ$sk$, $sk$He knows your interior life completely.$sk$, $sk$Al-Khabir means He is aware of the subtlest movements of your heart — the feelings you can't name, the doubts you're ashamed of. He knows, and He is not alarmed.$sk$, $sk$2026-04-07T18:33:44.135017+00:00$sk$::timestamptz),
  ($sk$al-khafid$sk$, $sk$Al-Khafid$sk$, $sk$الْخَافِضُ$sk$, $sk$He humbles what has grown too big.$sk$, $sk$Al-Khafid is the Abaser — the One who brings down the arrogant and the inflated. As Ar-Rafi lifts the humble, Al-Khafid lowers the inflated; two hands of the same wisdom, shaping what would otherwise destroy itself.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-khaliq$sk$, $sk$Al-Khaliq$sk$, $sk$الْخَالِقُ$sk$, $sk$You were made on purpose, by the One who knows what He's doing.$sk$, $sk$Al-Khaliq is the Creator — the One who shaped you with intention. You are not an accident. The features of your life that feel strange or hard were chosen, with care, by the One who designed everything.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-latif$sk$, $sk$Al-Latif$sk$, $sk$اللَّطِيفُ$sk$, $sk$He works in the details you cannot see.$sk$, $sk$Al-Latif is the Subtly Kind — the One who arranges things through small mercies and unseen movements. What looks like coincidence is often Al-Latif's hand.$sk$, $sk$2026-04-07T18:33:14.151294+00:00$sk$::timestamptz),
  ($sk$al-majeed$sk$, $sk$Al-Majeed$sk$, $sk$الْمَجِيدُ$sk$, $sk$His glory is gentle as much as it is grand.$sk$, $sk$Al-Majeed is the Glorious. His glory is paired with generosity — He is glorious in His giving, glorious in His pardoning. He does not crush the small ones who turn to Him; He honors them.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-majid$sk$, $sk$Al-Majid$sk$, $sk$الْمَاجِدُ$sk$, $sk$His nobility expresses itself as generosity toward you.$sk$, $sk$Al-Majid is the Noble — the One whose nobility shows through abundant kindness. He is generous not because He owes you, but because nobility is His nature. You are met with that nobility every day.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-malik$sk$, $sk$Al-Malik$sk$, $sk$الْمَلِكُ$sk$, $sk$He is sovereign over what feels out of your hands.$sk$, $sk$Al-Malik is the King — the One whose dominion never wavers. The kings of this world fail, but the One who rules over every atom of your life is steady. What feels chaotic to you is still under His command.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-mani$sk$, $sk$Al-Mani$sk$, $sk$الْمَانِعُ$sk$, $sk$What He withholds, He withholds for your protection.$sk$, $sk$Al-Mani is the Withholder — the One who prevents what would harm you, even when you wanted it. Many of your unanswered prayers are answered prayers; He said no because He saw what you could not.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-matin$sk$, $sk$Al-Matin$sk$, $sk$الْمَتِينُ$sk$, $sk$There is a steadiness beneath your feet.$sk$, $sk$Al-Matin is the Firm, the Steadfast. Nothing shakes Him. And those who hold to Him find that same firmness enters their own hearts.$sk$, $sk$2026-04-07T18:33:44.135017+00:00$sk$::timestamptz),
  ($sk$al-muakhkhir$sk$, $sk$Al-Muakhkhir$sk$, $sk$الْمُؤَخِّرُ$sk$, $sk$What He delays is not what He has denied.$sk$, $sk$Al-Muakhkhir is the Delayer — the One who postpones with purpose. The marriage, the child, the breakthrough that has not come yet is being held back by the same One who knows the perfect moment.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-mubdi$sk$, $sk$Al-Mubdi$sk$, $sk$الْمُبْدِئُ$sk$, $sk$Every beginning has come from Him.$sk$, $sk$Al-Mubdi is the Originator — the One who initiates creation without precedent. The new chapter you are stepping into, the fresh start you can barely imagine — He is the One who originates such openings.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-mughni$sk$, $sk$Al-Mughni$sk$, $sk$الْمُغْنِي$sk$, $sk$He enriches whoever He chooses to enrich.$sk$, $sk$Al-Mughni is the Enricher — the One who provides abundance, whether material or in the heart. He can make a poor person feel wealthy and a wealthy person feel empty. True richness is His gift.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-muhaymin$sk$, $sk$Al-Muhaymin$sk$, $sk$الْمُهَيْمِنُ$sk$, $sk$He watches over your life like a guardian, not a critic.$sk$, $sk$Al-Muhaymin is the Protector and Overseer. His watching is not surveillance — it is care. He keeps watch over what matters to you, including the parts of you that you have stopped guarding yourself.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-muhsi$sk$, $sk$Al-Muhsi$sk$, $sk$الْمُحْصِي$sk$, $sk$Not a single thing about you escapes His count.$sk$, $sk$Al-Muhsi is the Counter, the One who has precisely tallied every detail of every creature. Every breath you take, every step, every tear — He knows the number. You are not lost in the crowd.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-muhyi$sk$, $sk$Al-Muhyi$sk$, $sk$الْمُحْيِي$sk$, $sk$He gives life to what feels lifeless.$sk$, $sk$Al-Muhyi is the Giver of Life — the One who brings the dry land to life with rain and brings the dead heart to life with remembrance. What in you feels arid right now is not beyond His reviving touch.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-muid$sk$, $sk$Al-Muid$sk$, $sk$الْمُعِيدُ$sk$, $sk$He restores what has been undone.$sk$, $sk$Al-Muid is the Restorer — the One who returns what was lost or undone. He brings the body back after death, and He can bring back what you thought was permanently broken in this life too.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-muizz$sk$, $sk$Al-Muizz$sk$, $sk$الْمُعِزُّ$sk$, $sk$He grants honor that no one can take from you.$sk$, $sk$Al-Muizz is the Bestower of Honor — the One whose esteem is the only kind that endures. The world's regard fluctuates; His does not. The honor He gives is rooted in proximity to Him, not performance.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-mujib$sk$, $sk$Al-Mujib$sk$, $sk$الْمُجِيبُ$sk$, $sk$Your duas are being answered.$sk$, $sk$Al-Mujib is the Responsive One. Every sincere call is met — sometimes immediately, sometimes in a way you do not yet see. Keep asking.$sk$, $sk$2026-04-07T18:33:14.151294+00:00$sk$::timestamptz),
  ($sk$al-mumeet$sk$, $sk$Al-Mumeet$sk$, $sk$الْمُمِيتُ$sk$, $sk$Death is in His hands — and so is the life that follows.$sk$, $sk$Al-Mumeet is the One who causes death. Death is not random or cruel in His hand; it is timed precisely. And it is not the end — it is a transition into the next life under the same merciful Lord.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-mumin$sk$, $sk$Al-Mumin$sk$, $sk$الْمُؤْمِنُ$sk$, $sk$He is the source of every safety you have ever felt.$sk$, $sk$Al-Mumin is the Granter of Security. The peace you feel after fear, the steadiness after panic — these are gifts from Him. He grants the heart its sense of being safe even when the world is not.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-muqaddim$sk$, $sk$Al-Muqaddim$sk$, $sk$الْمُقَدِّمُ$sk$, $sk$He brings forward what is meant for you in His time.$sk$, $sk$Al-Muqaddim is the Expediter — the One who advances what He chooses. The things that come early in your life were not random; they were placed at the front for a reason you may understand later.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-muqeet$sk$, $sk$Al-Muqeet$sk$, $sk$الْمُقِيتُ$sk$, $sk$He sustains you in ways you don't see.$sk$, $sk$Al-Muqeet is the Nourisher — the One who provides what each creature needs to continue. Beyond food and money: He sustains your patience, your faith, your capacity to keep going. He is the source.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-muqsit$sk$, $sk$Al-Muqsit$sk$, $sk$الْمُقْسِطُ$sk$, $sk$He gives every soul exactly what is fair.$sk$, $sk$Al-Muqsit is the Equitable — the One who establishes balance. He sets right what was uneven. The unfair things you have endured will be measured and balanced under His scale, which never tilts.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-muqtadir$sk$, $sk$Al-Muqtadir$sk$, $sk$الْمُقْتَدِرُ$sk$, $sk$His power has no resistance it cannot overcome.$sk$, $sk$Al-Muqtadir is the Omnipotent — the One whose power is irresistible. Where Al-Qadir is able, Al-Muqtadir is dominant. What stands against His will does not stand for long.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-musawwir$sk$, $sk$Al-Musawwir$sk$, $sk$الْمُصَوِّرُ$sk$, $sk$Every detail of you was shaped on purpose.$sk$, $sk$Al-Musawwir is the Fashioner — the One who gives every created thing its specific form. Your face, your voice, your particular way of being in the world — these were not generic. They were drawn by Him, intentionally.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-mutaali$sk$, $sk$Al-Mutaali$sk$, $sk$الْمُتَعَالِ$sk$, $sk$He is above every limitation you can imagine.$sk$, $sk$Al-Mutaali is the Most Exalted — beyond every quality you might attribute to created things. He is not a larger version of anything in this world. He is uncontained, in a category of His own.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-mutakabbir$sk$, $sk$Al-Mutakabbir$sk$, $sk$الْمُتَكَبِّرُ$sk$, $sk$Greatness belongs to Him alone — and that is a relief.$sk$, $sk$Al-Mutakabbir is the Supreme. He alone is great by right, which means the pressure to be impressive is not yours to carry. You can be small. You can be ordinary. He is the One who is great.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-muzill$sk$, $sk$Al-Muzill$sk$, $sk$الْمُذِلُّ$sk$, $sk$He humbles whom He wills — paired with Al-Muizz, who honors whom He wills.$sk$, $sk$Al-Muzill is the One who humbles. He brings low the proud, and for the faithful, that lowering is itself a form of shaping — pulling them back from arrogance before it leads to a worse fall. The same hand that humbles also exalts: His sovereignty over honor is total.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-qabid$sk$, $sk$Al-Qabid$sk$, $sk$الْقَابِضُ$sk$, $sk$When provision is withheld, He is still at work.$sk$, $sk$Al-Qabid is the Withholder — the One who restricts according to wisdom. What is held back from you is not forgotten or punished; it is shaped. Restriction in His hand is preparation, not abandonment.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-qadir$sk$, $sk$Al-Qadir$sk$, $sk$الْقَادِرُ$sk$, $sk$He is able to do what looks impossible.$sk$, $sk$Al-Qadir is the Capable — the One who has the power to do whatever He wills. The outcome you cannot see a path to is one He can bring about with a single command. Kun fa yakun — Be, and it is.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-qahhar$sk$, $sk$Al-Qahhar$sk$, $sk$الْقَهَّارُ$sk$, $sk$Nothing can finally defeat what He has chosen.$sk$, $sk$Al-Qahhar is the Subduer — the One whose decree overrides every opposition. The forces arrayed against you, the obstacles that seem permanent — they bow before His will. He has the final word.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-qawi$sk$, $sk$Al-Qawi$sk$, $sk$الْقَوِيُّ$sk$, $sk$His strength is available to you.$sk$, $sk$Al-Qawi — the All-Strong — does not deplete. When your strength runs out, you are invited to draw from an inexhaustible source. Ask Him for it.$sk$, $sk$2026-04-07T18:33:44.135017+00:00$sk$::timestamptz),
  ($sk$al-qayyum$sk$, $sk$Al-Qayyum$sk$, $sk$الْقَيُّومُ$sk$, $sk$He is the only constant when everything shifts.$sk$, $sk$Al-Qayyum means self-subsisting and sustaining all things. When everything you lean on feels unstable, He is the one ground that cannot give way.$sk$, $sk$2026-04-07T18:33:44.135017+00:00$sk$::timestamptz),
  ($sk$al-quddus$sk$, $sk$Al-Quddus$sk$, $sk$الْقُدُّوسُ$sk$, $sk$There is a purity available to your heart.$sk$, $sk$Al-Quddus is the Most Holy, free of all imperfection. Connecting to Him is how the heart gets cleansed — not by your effort alone, but by proximity to the One who is pure.$sk$, $sk$2026-04-07T18:33:44.135017+00:00$sk$::timestamptz),
  ($sk$al-wadud$sk$, $sk$Al-Wadud$sk$, $sk$الْوَدُودُ$sk$, $sk$You are wired for deep, lasting love.$sk$, $sk$Al-Wadud means Allah loves with a love that does not waver or cool. The ache for real connection in you is a reflection of how He made you to be loved by Him.$sk$, $sk$2026-04-07T18:33:14.151294+00:00$sk$::timestamptz),
  ($sk$al-wahhab$sk$, $sk$Al-Wahhab$sk$, $sk$الْوَهَّابُ$sk$, $sk$He gives gifts you would never think to ask for.$sk$, $sk$Al-Wahhab is the Bestower — the One whose giving is pure gift, not reward. He bestows without expecting anything in return. The unexpected blessings in your life come from this Name.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-wahid$sk$, $sk$Al-Wahid$sk$, $sk$الْوَاحِدُ$sk$, $sk$He alone is One — and that is enough.$sk$, $sk$Al-Wahid is the One. There is no other, no second, no rival. The fragmentation you feel in chasing many things finds its rest in turning back to the One who is single, complete, sufficient.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-wajid$sk$, $sk$Al-Wajid$sk$, $sk$الْوَاجِدُ$sk$, $sk$Nothing He wants is beyond His reach.$sk$, $sk$Al-Wajid is the Finder — the One who never lacks. He is in need of nothing, and He has access to everything. When you ask Him for what you need, you are asking the One whose hand is never empty.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-wakil$sk$, $sk$Al-Wakil$sk$, $sk$الْوَكِيلُ$sk$, $sk$You can let go — He has it.$sk$, $sk$Al-Wakil is the Trustee, the One you hand your affairs over to completely. Hasbunallahu wa ni'mal wakil — Allah is enough for us, and He is the best Disposer of affairs.$sk$, $sk$2026-04-07T18:33:14.151294+00:00$sk$::timestamptz),
  ($sk$al-wali$sk$, $sk$Al-Wali$sk$, $sk$الْوَالِي$sk$, $sk$He governs your affairs whether you see Him or not.$sk$, $sk$Al-Wali is the Governor — the One who manages all matters. Even when you cannot trace His hand in your circumstances, He is administering them with care. Nothing in your life is unsupervised.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-waliyy$sk$, $sk$Al-Waliyy$sk$, $sk$الْوَلِيُّ$sk$, $sk$He is your closest ally — closer than any friend.$sk$, $sk$Al-Waliyy is the Protecting Friend, the Patron. The believers, the Quran says, have Allah as their Wali. He is not a distant deity but a near companion who takes your side and shelters you.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$al-wasi$sk$, $sk$Al-Wasi$sk$, $sk$الْوَاسِعُ$sk$, $sk$His mercy is wider than you can imagine.$sk$, $sk$Al-Wasi is the All-Encompassing — the One whose attributes have no edges. His mercy, His knowledge, His provision — none of them run out. There is always more than enough room in Him for what you bring.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$an-nafi$sk$, $sk$An-Nafi$sk$, $sk$النَّافِعُ$sk$, $sk$Every benefit you have ever received has come from Him.$sk$, $sk$An-Nafi is the Source of Benefit — the One who alone causes good to reach you. The people, opportunities, and resources that have helped you were all sent by Him. He is the giver behind every giver.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$an-nur$sk$, $sk$An-Nur$sk$, $sk$النُّورُ$sk$, $sk$His light finds you even in the dark.$sk$, $sk$An-Nur is the Light of the heavens and the earth. When you feel spiritually dim, it is not permanent — the same source of light that created the stars is available to your heart.$sk$, $sk$2026-04-07T18:33:14.151294+00:00$sk$::timestamptz),
  ($sk$ar-rafi$sk$, $sk$Ar-Rafi$sk$, $sk$الرَّافِعُ$sk$, $sk$He raises what has been lowered.$sk$, $sk$Ar-Rafi is the Exalter — the One who lifts up the humble, the unseen, the dismissed. The Quran's stories are full of those the world had no use for whom Allah raised. Your obscurity is not your destiny.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$ar-rahim$sk$, $sk$Ar-Rahim$sk$, $sk$الرَّحِيمُ$sk$, $sk$You are intimately, personally loved.$sk$, $sk$Where Ar-Rahman is mercy for all creation, Ar-Rahim is the mercy He reserves especially for believers. You are not just tolerated — you are treasured.$sk$, $sk$2026-04-07T18:33:14.151294+00:00$sk$::timestamptz),
  ($sk$ar-rahman$sk$, $sk$Ar-Rahman$sk$, $sk$الرَّحْمَٰنُ$sk$, $sk$You are held by infinite mercy.$sk$, $sk$Ar-Rahman is the name Allah chose for Himself above all others. Return to it whenever you feel unworthy — His mercy is not earned, it simply is.$sk$, $sk$2026-04-07T18:33:14.151294+00:00$sk$::timestamptz),
  ($sk$ar-raqeeb$sk$, $sk$Ar-Raqeeb$sk$, $sk$الرَّقِيبُ$sk$, $sk$He is attentive to you, not just aware of you.$sk$, $sk$Ar-Raqeeb is the Watchful — the One whose attention never drifts. He is not passively observing your life from far away. He is attending to it, moment by moment, with the focus of One who deeply cares.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$ar-rasheed$sk$, $sk$Ar-Rasheed$sk$, $sk$الرَّشِيدُ$sk$, $sk$He guides you toward what is genuinely right for you.$sk$, $sk$Ar-Rasheed is the Guide to right conduct — the One who directs you not just away from sin but toward the wise path. The clarity you feel after a long confusion is His guidance arriving.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$ar-rauf$sk$, $sk$Ar-Rauf$sk$, $sk$الرَّءُوفُ$sk$, $sk$His tenderness toward you is gentler than you know.$sk$, $sk$Ar-Rauf is the Most Compassionate — softer than Ar-Rahim, more delicate. His care is the kind that does not bruise. He handles your wounds with the gentleness a parent would not even know to use.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$ar-razzaq$sk$, $sk$Ar-Razzaq$sk$, $sk$الرَّزَّاقُ$sk$, $sk$Your provision has already been written.$sk$, $sk$Ar-Razzaq — the Provider — has already decreed every provision that will ever reach you. Work, but release the grip of anxiety: what is yours will not pass you by.$sk$, $sk$2026-04-07T18:33:44.135017+00:00$sk$::timestamptz),
  ($sk$as-sabur$sk$, $sk$As-Sabur$sk$, $sk$الصَّبُورُ$sk$, $sk$The wait is not a sign that He has forgotten you.$sk$, $sk$As-Sabur — the Patient One — never rushes His decree out of frustration. His timing is not delay; it is precision. And He gives you the strength to endure it.$sk$, $sk$2026-04-07T18:33:14.151294+00:00$sk$::timestamptz),
  ($sk$as-salam$sk$, $sk$As-Salam$sk$, $sk$السَّلَامُ$sk$, $sk$Peace is a person you can return to.$sk$, $sk$As-Salam is not just a greeting — it is a Name. Allah Himself is the source of all peace. The stillness you are searching for lives in closeness to Him.$sk$, $sk$2026-04-07T18:33:44.135017+00:00$sk$::timestamptz),
  ($sk$as-samad$sk$, $sk$As-Samad$sk$, $sk$الصَّمَدُ$sk$, $sk$He is the only One who can truly fill what is empty.$sk$, $sk$As-Samad means the Self-Sufficient Master whom all depend on. Every longing, every unfilled place in you — it points toward the One it was designed for.$sk$, $sk$2026-04-07T18:33:44.135017+00:00$sk$::timestamptz),
  ($sk$as-sami$sk$, $sk$As-Sami'$sk$, $sk$السَّمِيعُ$sk$, $sk$Every word you speak to Him lands.$sk$, $sk$As-Sami' — the All-Hearing — means not a single dua is lost in the air. Even your half-formed prayers, your silent ones, the ones that are just feelings — He hears them all.$sk$, $sk$2026-04-07T18:33:14.151294+00:00$sk$::timestamptz),
  ($sk$ash-shafi$sk$, $sk$Ash-Shafi$sk$, $sk$الشَّافِي$sk$, $sk$Healing — of every kind — is in His hands.$sk$, $sk$Ash-Shafi is the Healer. No wound is beyond Him — physical, emotional, spiritual. The Prophet ﷺ said: there is no disease He created except He also created its cure.$sk$, $sk$2026-04-07T18:33:44.135017+00:00$sk$::timestamptz),
  ($sk$ash-shahid$sk$, $sk$Ash-Shahid$sk$, $sk$الشَّهِيدُ$sk$, $sk$He is a witness to everything you endure.$sk$, $sk$Ash-Shahid is the Witness. Nothing you go through is unobserved. Every moment of patience, every private struggle — He sees it all and will account for it.$sk$, $sk$2026-04-07T18:33:44.135017+00:00$sk$::timestamptz),
  ($sk$ash-shakur$sk$, $sk$Ash-Shakur$sk$, $sk$الشَّكُورُ$sk$, $sk$Every act of gratitude multiplies what you have.$sk$, $sk$Ash-Shakur means Allah Himself is grateful — He amplifies and rewards the smallest good deeds beyond what they deserve. Gratitude is one of the most powerful postures you can take.$sk$, $sk$2026-04-07T18:33:44.135017+00:00$sk$::timestamptz),
  ($sk$at-tawwab$sk$, $sk$At-Tawwab$sk$, $sk$التَّوَّابُ$sk$, $sk$The door of return is always open.$sk$, $sk$At-Tawwab means Allah turns to His servant the moment the servant turns to Him. You do not have to earn your way back — the turning itself is the beginning.$sk$, $sk$2026-04-07T18:33:14.151294+00:00$sk$::timestamptz),
  ($sk$az-zahir$sk$, $sk$Az-Zahir$sk$, $sk$الظَّاهِرُ$sk$, $sk$Signs of Him are everywhere, if you look.$sk$, $sk$Az-Zahir is the Manifest — the One whose existence is evidenced by every created thing. The order in a leaf, the kindness of a stranger, the timing of a moment — they all carry traces of Him.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$dhul-jalali-wal-ikram$sk$, $sk$Dhul-Jalali wal-Ikram$sk$, $sk$ذُو الْجَلَالِ وَالْإِكْرَامِ$sk$, $sk$He is both awe-inspiring and overwhelmingly generous.$sk$, $sk$Dhul-Jalali wal-Ikram means Lord of Majesty and Bounty. He is great enough to inspire awe, and yet generous enough to lavish honor on you. Both qualities coexist in Him without contradiction.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz),
  ($sk$malik-ul-mulk$sk$, $sk$Malik-ul-Mulk$sk$, $sk$مَالِكُ الْمُلْكِ$sk$, $sk$All ownership belongs to Him alone.$sk$, $sk$Malik-ul-Mulk is the Owner of all dominion. Every kingdom, every wealth, every position of power — they are all His to give and take. What was given to you is on loan; what was taken was His to take back.$sk$, $sk$2026-05-12T00:00:00.000000+00:00$sk$::timestamptz);

commit;

-- Verification (run after applying):
-- select count(*) from public.name_anchors; -- expect 98
-- select count(*) from public.name_anchors where name_key in ('al-qarib','ar-rabb','al-jamil'); -- expect 0
-- select name_key from public.name_anchors order by name_key limit 5;