class AllahName {
  final int id;
  final String arabic;
  final String transliteration;
  final String english;
  final String meaning;
  final String lesson;

  const AllahName({
    required this.id,
    required this.arabic,
    required this.transliteration,
    required this.english,
    required this.meaning,
    required this.lesson,
  });
}

const List<AllahName> allahNames = [
  AllahName(
    id: 1,
    arabic: 'الرَّحْمَنُ',
    transliteration: 'Ar-Rahman',
    english: 'The Most Gracious',
    meaning: 'The One whose mercy encompasses all creation without condition.',
    lesson: 'His mercy precedes His wrath. Every moment you breathe is a gift from Ar-Rahman.',
  ),
  AllahName(
    id: 2,
    arabic: 'الرَّحِيمُ',
    transliteration: 'Ar-Raheem',
    english: 'The Most Merciful',
    meaning: 'The One whose special mercy is reserved for the believers.',
    lesson: 'Even when you feel distant, Ar-Raheem is drawing you back with mercy.',
  ),
  AllahName(
    id: 3,
    arabic: 'الْمَلِكُ',
    transliteration: 'Al-Malik',
    english: 'The King',
    meaning: 'The absolute sovereign who owns and governs all existence.',
    lesson: 'When the world\'s kings fail you, Al-Malik never abandons His servants.',
  ),
  AllahName(
    id: 4,
    arabic: 'الْقُدُّوسُ',
    transliteration: 'Al-Quddus',
    english: 'The Most Holy',
    meaning: 'The One free from all imperfection, deficiency, and fault.',
    lesson: 'In a world full of imperfection, Al-Quddus is your anchor of purity.',
  ),
  AllahName(
    id: 5,
    arabic: 'السَّلَامُ',
    transliteration: 'As-Salam',
    english: 'The Source of Peace',
    meaning: 'The One from whom all peace flows and in whom all peace rests.',
    lesson: 'True peace is not the absence of struggle — it is As-Salam dwelling in your heart.',
  ),
  AllahName(
    id: 6,
    arabic: 'الْمُؤْمِنُ',
    transliteration: 'Al-Mumin',
    english: 'The Guardian of Faith',
    meaning: 'The One who grants safety and confirms the faith of His servants.',
    lesson: 'Al-Mumin sees your sincerity even when others doubt you.',
  ),
  AllahName(
    id: 7,
    arabic: 'الْعَزِيزُ',
    transliteration: 'Al-Azeez',
    english: 'The Almighty',
    meaning: 'The One of perfect might and honor who is never overcome.',
    lesson: 'Lean on Al-Azeez. You are not weak when you call upon Him.',
  ),
  AllahName(
    id: 8,
    arabic: 'الْجَبَّارُ',
    transliteration: 'Al-Jabbar',
    english: 'The Compeller',
    meaning: 'The One who mends what is broken and compels all to His will.',
    lesson: 'Al-Jabbar heals broken hearts. Bring Him your shattered pieces.',
  ),
  AllahName(
    id: 9,
    arabic: 'الْخَالِقُ',
    transliteration: 'Al-Khaliq',
    english: 'The Creator',
    meaning: 'The One who brings everything into existence from nothing.',
    lesson: 'You are not an accident. Al-Khaliq designed every detail of you with purpose.',
  ),
  AllahName(
    id: 10,
    arabic: 'الْغَفَّارُ',
    transliteration: 'Al-Ghaffar',
    english: 'The Ever-Forgiving',
    meaning: 'The One who forgives sins repeatedly and covers faults completely.',
    lesson: 'Al-Ghaffar\'s door never closes. Return as many times as you fall.',
  ),
  AllahName(
    id: 11,
    arabic: 'الْوَهَّابُ',
    transliteration: 'Al-Wahhab',
    english: 'The Bestower',
    meaning: 'The One who gives endlessly without expecting anything in return.',
    lesson: 'Every gift you have — talent, love, breath — is from Al-Wahhab.',
  ),
  AllahName(
    id: 12,
    arabic: 'الرَّزَّاقُ',
    transliteration: 'Ar-Razzaq',
    english: 'The Provider',
    meaning: 'The One who provides all sustenance, seen and unseen.',
    lesson: 'Worry less. Ar-Razzaq has written your provision before you were born.',
  ),
  AllahName(
    id: 13,
    arabic: 'الْعَلِيمُ',
    transliteration: 'Al-Aleem',
    english: 'The All-Knowing',
    meaning: 'The One whose knowledge encompasses everything, hidden and apparent.',
    lesson: 'You never need to explain your pain to Al-Aleem. He already knows.',
  ),
  AllahName(
    id: 14,
    arabic: 'الْحَيُّ',
    transliteration: 'Al-Hayy',
    english: 'The Ever-Living',
    meaning: 'The One who has always lived and will never die.',
    lesson: 'Everything you lean on will pass away — except Al-Hayy.',
  ),
  AllahName(
    id: 15,
    arabic: 'الْقَيُّومُ',
    transliteration: 'Al-Qayyum',
    english: 'The Self-Sustaining',
    meaning: 'The One who sustains all of creation by His power.',
    lesson: 'You do not sustain yourself. Al-Qayyum holds you together even when you feel like falling apart.',
  ),
  AllahName(
    id: 16,
    arabic: 'النُّورُ',
    transliteration: 'An-Nur',
    english: 'The Light',
    meaning: 'The One who illuminates the heavens, the earth, and every heart.',
    lesson: 'When darkness surrounds you, An-Nur is the light that no shadow can extinguish.',
  ),
  AllahName(
    id: 17,
    arabic: 'الْمُهَيْمِنُ',
    transliteration: 'Al-Muhaymin',
    english: 'The Overseer',
    meaning: 'The One who watches over and protects all things.',
    lesson: 'Nothing escapes His watchful care. Al-Muhaymin guards what you cannot.',
  ),
  AllahName(
    id: 18,
    arabic: 'الْمُتَكَبِّرُ',
    transliteration: 'Al-Mutakabbir',
    english: 'The Supreme',
    meaning: 'The One whose greatness is beyond all comparison.',
    lesson: 'True greatness belongs only to Al-Mutakabbir. In recognizing this, you find humility.',
  ),
  AllahName(
    id: 19,
    arabic: 'الْبَارِئُ',
    transliteration: 'Al-Bari',
    english: 'The Evolver',
    meaning: 'The One who shapes creation according to His perfect plan.',
    lesson: 'Al-Bari is still shaping you. Your story is not finished yet.',
  ),
  AllahName(
    id: 20,
    arabic: 'الْمُصَوِّرُ',
    transliteration: 'Al-Musawwir',
    english: 'The Fashioner',
    meaning: 'The One who gives each creation its unique form and beauty.',
    lesson: 'Your face, your fingerprint, your soul — Al-Musawwir made you one of a kind.',
  ),
  AllahName(
    id: 21,
    arabic: 'الْقَهَّارُ',
    transliteration: 'Al-Qahhar',
    english: 'The Subduer',
    meaning: 'The One who overcomes all and to whom everything submits.',
    lesson: 'The tyrant you fear is nothing before Al-Qahhar.',
  ),
  AllahName(
    id: 22,
    arabic: 'الْفَتَّاحُ',
    transliteration: 'Al-Fattah',
    english: 'The Opener',
    meaning: 'The One who opens the doors of mercy, provision, and guidance.',
    lesson: 'When every door seems closed, Al-Fattah opens ways you never imagined.',
  ),
  AllahName(
    id: 23,
    arabic: 'الْقَابِضُ',
    transliteration: 'Al-Qabid',
    english: 'The Withholder',
    meaning: 'The One who contracts, withholds, and tests through scarcity.',
    lesson: 'Sometimes Al-Qabid withholds to protect you from what would harm you.',
  ),
  AllahName(
    id: 24,
    arabic: 'الْبَاسِطُ',
    transliteration: 'Al-Basit',
    english: 'The Expander',
    meaning: 'The One who expands, extends, and gives abundantly.',
    lesson: 'After every constriction comes expansion. Trust the rhythm of Al-Basit.',
  ),
  AllahName(
    id: 25,
    arabic: 'الْحَكِيمُ',
    transliteration: 'Al-Hakeem',
    english: 'The All-Wise',
    meaning: 'The One who acts with perfect wisdom in everything He decrees.',
    lesson: 'You may not understand the plan, but Al-Hakeem\'s wisdom never errs.',
  ),
  AllahName(
    id: 26,
    arabic: 'الْوَدُودُ',
    transliteration: 'Al-Wadud',
    english: 'The Most Loving',
    meaning: 'The One whose love for His servants is unconditional and constant.',
    lesson: 'Al-Wadud loves you not for your perfection but for your turning toward Him.',
  ),
  AllahName(
    id: 27,
    arabic: 'الشَّكُورُ',
    transliteration: 'Ash-Shakur',
    english: 'The Most Appreciative',
    meaning: 'The One who rewards abundantly for the smallest good deed.',
    lesson: 'Even your private acts of goodness are seen and multiplied by Ash-Shakur.',
  ),
  AllahName(
    id: 28,
    arabic: 'الْحَلِيمُ',
    transliteration: 'Al-Haleem',
    english: 'The Forbearing',
    meaning: 'The One who withholds punishment despite having full power to act.',
    lesson: 'That you are still here, still trying — this is Al-Haleem\'s patience with you.',
  ),
  AllahName(
    id: 29,
    arabic: 'الْكَرِيمُ',
    transliteration: 'Al-Kareem',
    english: 'The Most Generous',
    meaning: 'The One whose generosity is without limit or expectation.',
    lesson: 'Ask Al-Kareem without shame. His generosity is never depleted.',
  ),
  AllahName(
    id: 30,
    arabic: 'التَّوَّابُ',
    transliteration: 'At-Tawwab',
    english: 'The Acceptor of Repentance',
    meaning: 'The One who turns toward His servants when they turn toward Him.',
    lesson: 'You took one step back to Him — At-Tawwab is already running toward you.',
  ),
  AllahName(
    id: 31,
    arabic: 'الصَّبُورُ',
    transliteration: 'As-Sabur',
    english: 'The Patient',
    meaning: 'The One who is patient with the disobedience of His creation.',
    lesson: 'As-Sabur does not rush you. He waits for you with open arms.',
  ),
  AllahName(
    id: 32,
    arabic: 'الْهَادِي',
    transliteration: 'Al-Hadi',
    english: 'The Guide',
    meaning: 'The One who guides hearts to truth and feet to the straight path.',
    lesson: 'You are not lost. Al-Hadi placed the longing for guidance in your heart.',
  ),
  AllahName(
    id: 33,
    arabic: 'الصَّمَدُ',
    transliteration: 'As-Samad',
    english: 'The Eternal Refuge',
    meaning: 'The One to whom all creation turns in need, yet He needs nothing.',
    lesson: 'When you have nowhere to turn, As-Samad is the refuge that never turns you away.',
  ),
  AllahName(
    id: 34,
    arabic: 'الْوَكِيلُ',
    transliteration: 'Al-Wakeel',
    english: 'The Trustee',
    meaning: 'The One who is sufficient as a guardian and disposer of affairs.',
    lesson: 'Hand it over to Al-Wakeel. He manages what you cannot.',
  ),
  AllahName(
    id: 35,
    arabic: 'اللَّطِيفُ',
    transliteration: 'Al-Lateef',
    english: 'The Subtle',
    meaning: 'The One who is aware of the finest details and acts with gentleness.',
    lesson: 'Al-Lateef works in ways you cannot see, arranging what you cannot plan.',
  ),
  AllahName(
    id: 36,
    arabic: 'الْمُجِيبُ',
    transliteration: 'Al-Mujeeb',
    english: 'The Responsive',
    meaning: 'The One who answers the call of those who call upon Him.',
    lesson: 'Your dua was heard the moment your lips moved. Al-Mujeeb is already responding.',
  ),
  AllahName(
    id: 37,
    arabic: 'الشَّافِي',
    transliteration: 'Ash-Shafi',
    english: 'The Healer',
    meaning: 'The One who cures every illness of body and soul.',
    lesson: 'No wound is too deep for Ash-Shafi. He heals what medicine cannot reach.',
  ),
  AllahName(
    id: 38,
    arabic: 'الْحَفِيظُ',
    transliteration: 'Al-Hafeez',
    english: 'The Preserver',
    meaning: 'The One who guards and protects all things in His care.',
    lesson: 'Everything you love is in the hands of Al-Hafeez — even when you cannot hold it.',
  ),
  AllahName(
    id: 39,
    arabic: 'الرَّقِيبُ',
    transliteration: 'Ar-Raqeeb',
    english: 'The Watchful',
    meaning: 'The One who sees every action, thought, and intention.',
    lesson: 'Ar-Raqeeb sees the good you do in secret. Nothing is wasted.',
  ),
  AllahName(
    id: 40,
    arabic: 'الْخَافِضُ',
    transliteration: 'Al-Khafid',
    english: 'The Abaser',
    meaning: 'The One who lowers whoever He wills by His wisdom.',
    lesson: 'Al-Khafid humbles the arrogant and reminds us that all status belongs to Him.',
  ),
  AllahName(
    id: 41,
    arabic: 'الرَّافِعُ',
    transliteration: 'Ar-Rafi',
    english: 'The Exalter',
    meaning: 'The One who raises His servants in rank and honor.',
    lesson: 'Ar-Rafi elevates those who humble themselves before Him.',
  ),
  AllahName(
    id: 42,
    arabic: 'الْمُعِزُّ',
    transliteration: 'Al-Muizz',
    english: 'The Bestower of Honor',
    meaning: 'The One who gives honor and dignity to whom He wills.',
    lesson: 'True honor comes from Al-Muizz, not from people or positions.',
  ),
  AllahName(
    id: 43,
    arabic: 'الْمُذِلُّ',
    transliteration: 'Al-Muzill',
    english: 'The Humiliator',
    meaning: 'The One who disgraces those who defy His command.',
    lesson: 'Al-Muzill reminds us that no empire lasts without His permission.',
  ),
  AllahName(
    id: 44,
    arabic: 'السَّمِيعُ',
    transliteration: 'As-Sami',
    english: 'The All-Hearing',
    meaning: 'The One who hears every sound, whisper, and silent prayer.',
    lesson: 'Even the prayer you could not put into words — As-Sami heard it.',
  ),
  AllahName(
    id: 45,
    arabic: 'الْبَصِيرُ',
    transliteration: 'Al-Baseer',
    english: 'The All-Seeing',
    meaning: 'The One who sees all things, open and hidden.',
    lesson: 'Al-Baseer witnesses your struggle even when no one else does.',
  ),
  AllahName(
    id: 46,
    arabic: 'الْحَكَمُ',
    transliteration: 'Al-Hakam',
    english: 'The Judge',
    meaning: 'The One whose judgment is absolute and perfectly just.',
    lesson: 'When the world is unjust, remember that Al-Hakam will settle every account.',
  ),
  AllahName(
    id: 47,
    arabic: 'الْعَدْلُ',
    transliteration: 'Al-Adl',
    english: 'The Just',
    meaning: 'The One who is perfectly balanced in all He does.',
    lesson: 'Al-Adl will never wrong you — not by the weight of an atom.',
  ),
  AllahName(
    id: 48,
    arabic: 'الْخَبِيرُ',
    transliteration: 'Al-Khabeer',
    english: 'The All-Aware',
    meaning: 'The One who is aware of the inner reality of all things.',
    lesson: 'You do not need to pretend with Al-Khabeer. He knows your truth already.',
  ),
  AllahName(
    id: 49,
    arabic: 'الْعَظِيمُ',
    transliteration: 'Al-Azeem',
    english: 'The Magnificent',
    meaning: 'The One whose greatness is beyond human comprehension.',
    lesson: 'Your problems feel massive — until you remember the magnificence of Al-Azeem.',
  ),
  AllahName(
    id: 50,
    arabic: 'الْغَفُورُ',
    transliteration: 'Al-Ghafur',
    english: 'The Forgiving',
    meaning: 'The One who forgives and conceals faults with grace.',
    lesson: 'Al-Ghafur does not just forgive — He erases the sin as if it never happened.',
  ),
  AllahName(
    id: 51,
    arabic: 'الْعَلِيُّ',
    transliteration: 'Al-Ali',
    english: 'The Most High',
    meaning: 'The One who is above all creation in rank and majesty.',
    lesson: 'When you prostrate to Al-Ali, you reach the highest station a human can attain.',
  ),
  AllahName(
    id: 52,
    arabic: 'الْكَبِيرُ',
    transliteration: 'Al-Kabeer',
    english: 'The Greatest',
    meaning: 'The One who is greater than everything in existence.',
    lesson: 'Whatever towers over you in fear — Al-Kabeer is greater than it.',
  ),
  AllahName(
    id: 53,
    arabic: 'الْمُقِيتُ',
    transliteration: 'Al-Muqeet',
    english: 'The Nourisher',
    meaning: 'The One who nourishes and sustains every living thing.',
    lesson: 'Al-Muqeet feeds not only your body but your soul and your purpose.',
  ),
  AllahName(
    id: 54,
    arabic: 'الْحَسِيبُ',
    transliteration: 'Al-Haseeb',
    english: 'The Reckoner',
    meaning: 'The One who takes account of all deeds with precision.',
    lesson: 'Al-Haseeb counts every kindness. Nothing good is ever lost.',
  ),
  AllahName(
    id: 55,
    arabic: 'الْجَلِيلُ',
    transliteration: 'Al-Jaleel',
    english: 'The Majestic',
    meaning: 'The One of overwhelming majesty and grandeur.',
    lesson: 'Stand in awe of Al-Jaleel, and the things you feared will shrink.',
  ),
  AllahName(
    id: 56,
    arabic: 'الْوَاسِعُ',
    transliteration: 'Al-Wasi',
    english: 'The All-Encompassing',
    meaning: 'The One whose mercy, knowledge, and provision encompass everything.',
    lesson: 'Your need is never too big for Al-Wasi. His capacity has no limit.',
  ),
  AllahName(
    id: 57,
    arabic: 'الْمَجِيدُ',
    transliteration: 'Al-Majeed',
    english: 'The Glorious',
    meaning: 'The One who is glorious and generous in all His actions.',
    lesson: 'Al-Majeed combines greatness with generosity — He is both awe-inspiring and giving.',
  ),
  AllahName(
    id: 58,
    arabic: 'الْبَاعِثُ',
    transliteration: 'Al-Baith',
    english: 'The Resurrector',
    meaning: 'The One who raises the dead and brings all to account.',
    lesson: 'Al-Baith can revive a dead heart just as He will raise the dead on the Last Day.',
  ),
  AllahName(
    id: 59,
    arabic: 'الشَّهِيدُ',
    transliteration: 'Ash-Shaheed',
    english: 'The Witness',
    meaning: 'The One who witnesses all things at all times.',
    lesson: 'Your silent sacrifice is not unseen. Ash-Shaheed was there.',
  ),
  AllahName(
    id: 60,
    arabic: 'الْحَقُّ',
    transliteration: 'Al-Haqq',
    english: 'The Truth',
    meaning: 'The One who is the ultimate reality and absolute truth.',
    lesson: 'In a world of illusions, Al-Haqq is the only certainty you need.',
  ),
  AllahName(
    id: 61,
    arabic: 'الْقَوِيُّ',
    transliteration: 'Al-Qawiyy',
    english: 'The Strong',
    meaning: 'The One whose strength is unlimited and never weakens.',
    lesson: 'When you feel powerless, Al-Qawiyy lends strength to those who rely on Him.',
  ),
  AllahName(
    id: 62,
    arabic: 'الْمَتِينُ',
    transliteration: 'Al-Mateen',
    english: 'The Firm',
    meaning: 'The One whose power is unshakeable and inexhaustible.',
    lesson: 'When everything around you is shaking, Al-Mateen is the unshakeable ground.',
  ),
  AllahName(
    id: 63,
    arabic: 'الْوَلِيُّ',
    transliteration: 'Al-Waliyy',
    english: 'The Protecting Friend',
    meaning: 'The One who is the helper and protector of the believers.',
    lesson: 'You are never alone. Al-Waliyy is closer to you than your own loneliness.',
  ),
  AllahName(
    id: 64,
    arabic: 'الْحَمِيدُ',
    transliteration: 'Al-Hameed',
    english: 'The Praiseworthy',
    meaning: 'The One who is worthy of all praise in every situation.',
    lesson: 'Even in hardship, Al-Hameed deserves praise — and praising Him transforms the hardship.',
  ),
  AllahName(
    id: 65,
    arabic: 'الْمُحْصِي',
    transliteration: 'Al-Muhsi',
    english: 'The Counter',
    meaning: 'The One who counts and records everything with precision.',
    lesson: 'Al-Muhsi has numbered every tear you have shed. None are forgotten.',
  ),
  AllahName(
    id: 66,
    arabic: 'الْمُبْدِئُ',
    transliteration: 'Al-Mubdi',
    english: 'The Originator',
    meaning: 'The One who begins creation without any prior model.',
    lesson: 'Al-Mubdi created you as something entirely new. You are not a copy.',
  ),
  AllahName(
    id: 67,
    arabic: 'الْمُعِيدُ',
    transliteration: 'Al-Muid',
    english: 'The Restorer',
    meaning: 'The One who brings back creation after its end.',
    lesson: 'What was taken from you — Al-Muid can restore it, or replace it with better.',
  ),
  AllahName(
    id: 68,
    arabic: 'الْمُحْيِي',
    transliteration: 'Al-Muhyi',
    english: 'The Giver of Life',
    meaning: 'The One who gives life to the dead and to all living things.',
    lesson: 'Al-Muhyi can breathe life into your hopes when they feel dead.',
  ),
  AllahName(
    id: 69,
    arabic: 'الْمُمِيتُ',
    transliteration: 'Al-Mumeet',
    english: 'The Bringer of Death',
    meaning: 'The One who takes life at its appointed time.',
    lesson: 'Al-Mumeet reminds us that this world is temporary — live for what lasts.',
  ),
  AllahName(
    id: 70,
    arabic: 'الْوَاجِدُ',
    transliteration: 'Al-Wajid',
    english: 'The Finder',
    meaning: 'The One who finds whatever He wills and lacks nothing.',
    lesson: 'Al-Wajid is never at a loss. He always finds a way for you.',
  ),
  AllahName(
    id: 71,
    arabic: 'الْمَاجِدُ',
    transliteration: 'Al-Majid',
    english: 'The Noble',
    meaning: 'The One whose nobility and generosity overflow.',
    lesson: 'Al-Majid treats you with a generosity you could never earn.',
  ),
  AllahName(
    id: 72,
    arabic: 'الْوَاحِدُ',
    transliteration: 'Al-Wahid',
    english: 'The One',
    meaning: 'The One who is unique and without partner in His essence.',
    lesson: 'Al-Wahid is the only One who will never let you down.',
  ),
  AllahName(
    id: 73,
    arabic: 'الْأَحَدُ',
    transliteration: 'Al-Ahad',
    english: 'The Unique',
    meaning: 'The One who is absolutely singular, indivisible, and incomparable.',
    lesson: 'Nothing compares to Al-Ahad. And nothing compares to the peace of knowing Him.',
  ),
  AllahName(
    id: 74,
    arabic: 'الْقَادِرُ',
    transliteration: 'Al-Qadir',
    english: 'The Capable',
    meaning: 'The One who has power over all things without effort.',
    lesson: 'What seems impossible to you is effortless for Al-Qadir.',
  ),
  AllahName(
    id: 75,
    arabic: 'الْمُقْتَدِرُ',
    transliteration: 'Al-Muqtadir',
    english: 'The Omnipotent',
    meaning: 'The One who prevails over all things through His absolute power.',
    lesson: 'Al-Muqtadir has power even over the things that overpower you.',
  ),
  AllahName(
    id: 76,
    arabic: 'الْمُقَدِّمُ',
    transliteration: 'Al-Muqaddim',
    english: 'The Expediter',
    meaning: 'The One who brings forward whatever He wills.',
    lesson: 'Al-Muqaddim advances what is good for you, even when you cannot see the timing.',
  ),
  AllahName(
    id: 77,
    arabic: 'الْمُؤَخِّرُ',
    transliteration: 'Al-Muakhkhir',
    english: 'The Delayer',
    meaning: 'The One who delays whatever He wills in His wisdom.',
    lesson: 'What Al-Muakhkhir delays is not denied — it is being perfected.',
  ),
  AllahName(
    id: 78,
    arabic: 'الْأَوَّلُ',
    transliteration: 'Al-Awwal',
    english: 'The First',
    meaning: 'The One who existed before all creation, with no beginning.',
    lesson: 'Before your worries existed, Al-Awwal was already there with the solution.',
  ),
  AllahName(
    id: 79,
    arabic: 'الْآخِرُ',
    transliteration: 'Al-Akhir',
    english: 'The Last',
    meaning: 'The One who remains after all creation has perished.',
    lesson: 'Everything ends — except Al-Akhir. Invest in what reaches Him.',
  ),
  AllahName(
    id: 80,
    arabic: 'الظَّاهِرُ',
    transliteration: 'Az-Zahir',
    english: 'The Manifest',
    meaning: 'The One whose existence is evident in all creation.',
    lesson: 'Look at the sky, the mountains, a newborn — Az-Zahir is manifest everywhere.',
  ),
  AllahName(
    id: 81,
    arabic: 'الْبَاطِنُ',
    transliteration: 'Al-Batin',
    english: 'The Hidden',
    meaning: 'The One who is hidden from human perception yet closer than all.',
    lesson: 'Al-Batin is invisible to the eyes but unmistakable to the heart.',
  ),
  AllahName(
    id: 82,
    arabic: 'الْوَالِي',
    transliteration: 'Al-Wali',
    english: 'The Governor',
    meaning: 'The One who governs and manages all affairs.',
    lesson: 'Al-Wali is running everything. You can rest.',
  ),
  AllahName(
    id: 83,
    arabic: 'الْمُتَعَالِ',
    transliteration: 'Al-Mutaali',
    english: 'The Most Exalted',
    meaning: 'The One who is exalted above all that creation ascribes to Him.',
    lesson: 'No matter how grand your conception of God — Al-Mutaali is greater.',
  ),
  AllahName(
    id: 84,
    arabic: 'الْبَرُّ',
    transliteration: 'Al-Barr',
    english: 'The Source of Goodness',
    meaning: 'The One who is the source of all kindness and benevolence.',
    lesson: 'Every good thing in your life traces back to Al-Barr.',
  ),
  AllahName(
    id: 85,
    arabic: 'الْعَفُوُّ',
    transliteration: 'Al-Afuw',
    english: 'The Pardoner',
    meaning: 'The One who erases sins completely, as if they never happened.',
    lesson: 'Al-Afuw doesn\'t just forgive — He wipes the slate clean entirely.',
  ),
  AllahName(
    id: 86,
    arabic: 'الرَّءُوفُ',
    transliteration: 'Ar-Rauf',
    english: 'The Compassionate',
    meaning: 'The One whose compassion is tender and overwhelmingly gentle.',
    lesson: 'Ar-Rauf\'s compassion is softer than a mother\'s — and He never tires of it.',
  ),
  AllahName(
    id: 87,
    arabic: 'مَالِكُ الْمُلْكِ',
    transliteration: 'Malik-ul-Mulk',
    english: 'Owner of Sovereignty',
    meaning: 'The One who owns all dominion and grants it to whom He wills.',
    lesson: 'Kingdoms rise and fall by the decree of Malik-ul-Mulk alone.',
  ),
  AllahName(
    id: 88,
    arabic: 'ذُو الْجَلَالِ وَالْإِكْرَامِ',
    transliteration: 'Dhul-Jalali wal-Ikram',
    english: 'Lord of Majesty and Bounty',
    meaning: 'The One who possesses both overwhelming majesty and abundant generosity.',
    lesson: 'He is both awe-inspiring and intimately generous. Majesty and mercy, together.',
  ),
  AllahName(
    id: 89,
    arabic: 'الْمُقْسِطُ',
    transliteration: 'Al-Muqsit',
    english: 'The Equitable',
    meaning: 'The One who acts with perfect fairness and justice.',
    lesson: 'Al-Muqsit will balance every scale. Justice will come.',
  ),
  AllahName(
    id: 90,
    arabic: 'الْجَامِعُ',
    transliteration: 'Al-Jami',
    english: 'The Gatherer',
    meaning: 'The One who gathers all creation on the Day of Judgment.',
    lesson: 'Al-Jami will bring together what was scattered — including your broken pieces.',
  ),
  AllahName(
    id: 91,
    arabic: 'الْغَنِيُّ',
    transliteration: 'Al-Ghaniyy',
    english: 'The Self-Sufficient',
    meaning: 'The One who is free of all needs and upon whom all depend.',
    lesson: 'Al-Ghaniyy needs nothing from you — yet He invites you to ask.',
  ),
  AllahName(
    id: 92,
    arabic: 'الْمُغْنِي',
    transliteration: 'Al-Mughni',
    english: 'The Enricher',
    meaning: 'The One who enriches whom He wills and frees them from need.',
    lesson: 'True richness is when Al-Mughni fills your heart, not just your hands.',
  ),
  AllahName(
    id: 93,
    arabic: 'الْمَانِعُ',
    transliteration: 'Al-Mani',
    english: 'The Withholder',
    meaning: 'The One who prevents harm and withholds what would not benefit.',
    lesson: 'What Al-Mani withholds from you is also a form of His protection.',
  ),
  AllahName(
    id: 94,
    arabic: 'الضَّارُّ',
    transliteration: 'Ad-Darr',
    english: 'The Distresser',
    meaning: 'The One who creates difficulty as a means of growth and return.',
    lesson: 'The pain you feel is not pointless — Ad-Darr uses it to bring you back.',
  ),
  AllahName(
    id: 95,
    arabic: 'النَّافِعُ',
    transliteration: 'An-Nafi',
    english: 'The Benefiter',
    meaning: 'The One who creates benefit and good for His servants.',
    lesson: 'An-Nafi placed benefit in places you have not yet looked.',
  ),
  AllahName(
    id: 96,
    arabic: 'الْبَدِيعُ',
    transliteration: 'Al-Badi',
    english: 'The Originator of the Heavens',
    meaning: 'The One who creates wonders without any prior model or material.',
    lesson: 'Al-Badi is endlessly creative. Your next chapter can be unlike anything before.',
  ),
  AllahName(
    id: 97,
    arabic: 'الْبَاقِي',
    transliteration: 'Al-Baqi',
    english: 'The Everlasting',
    meaning: 'The One who remains forever after all creation has perished.',
    lesson: 'Attach your heart to Al-Baqi — everything else will pass away.',
  ),
  AllahName(
    id: 98,
    arabic: 'الرَّشِيدُ',
    transliteration: 'Ar-Rasheed',
    english: 'The Guide to Right Path',
    meaning: 'The One who directs all affairs toward their right conclusion.',
    lesson: 'Ar-Rasheed is guiding your story to a conclusion better than you could write.',
  ),
];

AllahName getTodaysName() {
  final now = DateTime.now();
  final startOfYear = DateTime(now.year, 1, 1);
  final dayOfYear = now.difference(startOfYear).inDays;
  return allahNames[dayOfYear % allahNames.length];
}

/// Stable kebab-case key for [name], used as the home-screen widget's deep-link
/// hint and payload identity (see `WidgetDataService`).
///
/// NOTE: the AUTHORITATIVE app↔widget daily-Name catalog is generated at build
/// time from THIS same `allahNames` list (spec §10.1 / task T7), so the widget's
/// offline daily fallback indexes `dayOfYear % 99` into an identically-ordered
/// catalog. This helper only produces the personalized-payload key + deep link,
/// where the app also passes the resolved Name fields directly.
String widgetNameKeyFor(AllahName name) => name.transliteration
    .toLowerCase()
    .replaceAll(RegExp(r'[^a-z0-9]+'), '-')
    .replaceAll(RegExp(r'^-+|-+$'), '');
