// Sakina companion widget — the living lantern (fānūs) whose light reflects the
// muḥāsabah streak (Phase 3 of the streaks + companion plan).
//
// WidgetKit can't run the Flutter CustomPainter or animate, so the lantern is a
// set of PRE-RENDERED PNG frames — one per (skin × brightness), named
// companion_<skinId>_<brightness>.png and generated by
// `GEN_WIDGET_FRAMES=1 flutter test test/widgets/gen_companion_skin_frames_test.dart`.
// The widget picks the frame for the current streak state AND the equipped skin
// (read from the payload's `lantern_skin` key), then composites the live streak
// number + a reverent label as SwiftUI on top. Skin resolution and the asset
// fallback chain live in CompanionSkinResolver.swift (unit-tested); backdrops
// are in-app only and never reach the widget (spec §5).
//
// It reads the SAME App-Group payload the Name widget uses
// (sakina_widget_payload); no new Dart payload fields. The brightness mapping
// below mirrors lib/features/streaks/companion_state_mapper.dart as closely as
// the payload allows (the payload has streak + checked_in but not
// longest/lastActive/freezeOwned, so streak==0 shows the inviting endowedDim
// rather than a cold dormant, and there's no freeze-shield overlay here).
//
// Auto-bundled: ios/SakinaWidget/ is a Xcode-16 file-system-synchronized group,
// so this file and the companion_*.png frames compile/bundle with no manual
// "add to target" (see SETUP.md).

import SwiftUI
import WidgetKit

private let kAppGroupId = "group.com.sakina.app.widget"
private let kPayloadKey = "sakina_widget_payload"
private let kCompanionKind = "SakinaCompanionWidget"

private enum CPalette {
    static let cream = Color(red: 0.984, green: 0.969, blue: 0.949)   // #FBF7F2
    static let emerald = Color(red: 0.106, green: 0.420, blue: 0.290) // #1B6B4A
    static let goldInk = Color(red: 0.604, green: 0.435, blue: 0.216) // #9A6F37
    static let ink = Color(red: 0.173, green: 0.165, blue: 0.149)     // #2C2A26
    static let amber = Color(red: 0.910, green: 0.631, blue: 0.329)   // #E8A154
}

// MARK: - Payload (subset of the shared widget payload)
//
// `CompanionPayload` + `decodeCompanionPayload` live in CompanionSkinResolver.swift
// so they can be unit-tested by the swiftc harness.

private func loadCompanionPayload() -> CompanionPayload? {
    guard let defaults = UserDefaults(suiteName: kAppGroupId) else { return nil }
    return decodeCompanionPayload(defaults.string(forKey: kPayloadKey))
}

private func isSameLocalDay(_ isoString: String, _ date: Date, _ cal: Calendar) -> Bool {
    let fmt = ISO8601DateFormatter()
    fmt.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
    let parsed = fmt.date(from: isoString) ?? ISO8601DateFormatter().date(from: isoString)
    guard let parsed = parsed else { return false }
    return cal.isDate(parsed, inSameDayAs: date)
}

// MARK: - State model

private enum RenderPhase { case current, eveningAtRisk, nextDay }

private struct CompanionDisplay {
    let brightness: String   // frame key: "endowedDim", "dim", ...
    let skin: String         // lantern skin id: "classic_gold", "obsidian_gold", ...
    let streak: Int
    let checkedIn: Bool
    let loggedOut: Bool
    let atRisk: Bool
}

/// Mirror of resolveCompanionState (payload-limited). streak==0 → endowedDim
/// (never a cold Day 0 on the always-visible widget).
private func resolveCompanion(at date: Date, phase: RenderPhase) -> CompanionDisplay {
    let cal = Calendar.current
    let payload = loadCompanionPayload()
    guard let p = payload else {
        return CompanionDisplay(brightness: "endowedDim", skin: kDefaultLanternSkinId,
                                streak: 0, checkedIn: false, loggedOut: true,
                                atRisk: false)
    }
    let checkedIn = p.checked_in_today && p.mode == "personalized"
        && isSameLocalDay(p.updated_at, date, cal)
    let streak = p.streak
    // At-risk mirrors the Dart mapper's local-hour split (companionAtRiskHour =
    // 20): un-lit AND at/after 8pm local. Derive it from the entry's own hour so
    // a `.current` snapshot rendered after 8pm still reads at-risk — not only the
    // scheduled `.eveningAtRisk` entry (which isn't produced when the timeline is
    // built after 8pm).
    let hour = cal.component(.hour, from: date)
    let atRisk = !checkedIn && (phase == .eveningAtRisk || hour >= 20)

    let brightness: String
    if streak <= 0 {
        brightness = "endowedDim"
    } else if checkedIn {
        if streak <= 3 { brightness = "dim" }
        else if streak <= 29 { brightness = "glowing" }
        else { brightness = "fullyLit" }
    } else {
        brightness = atRisk ? "atRiskUnlit" : "pendingUnlit"
    }
    return CompanionDisplay(brightness: brightness,
                            skin: sanitizedLanternSkinId(p.lantern_skin),
                            streak: streak, checkedIn: checkedIn,
                            loggedOut: false, atRisk: atRisk)
}

private func companionImage(skinId: String, brightness: String) -> Image? {
    for name in companionAssetCandidates(skinId: skinId, brightness: brightness) {
        if let url = Bundle.main.url(forResource: name, withExtension: "png"),
           let data = try? Data(contentsOf: url),
           let ui = UIImage(data: data) {
            return Image(uiImage: ui)
        }
    }
    return nil
}

// MARK: - Copy (reverent — istiqāmah, never "don't lose it")

private func statusLine(_ d: CompanionDisplay) -> String {
    if d.loggedOut { return "Your light is ready" }
    if d.streak <= 0 { return "Begin your muḥāsabah" }
    if d.checkedIn { return "Lit — may Allah keep you steadfast" }
    return d.atRisk ? "Still time today to relight it"
                    : "Reflect today to relight your lantern"
}

private func shortLabel(_ d: CompanionDisplay) -> String {
    if d.loggedOut || d.streak <= 0 { return "Begin" }
    if d.checkedIn { return "Day \(d.streak)" }
    return "Reflect"
}

// MARK: - Timeline

private struct CompanionEntry: TimelineEntry {
    let date: Date
    let display: CompanionDisplay
}

private struct CompanionProvider: TimelineProvider {
    func placeholder(in context: Context) -> CompanionEntry {
        CompanionEntry(date: Date(), display: resolveCompanion(at: Date(), phase: .current))
    }
    func getSnapshot(in context: Context, completion: @escaping (CompanionEntry) -> Void) {
        completion(CompanionEntry(date: Date(), display: resolveCompanion(at: Date(), phase: .current)))
    }
    func getTimeline(in context: Context, completion: @escaping (Timeline<CompanionEntry>) -> Void) {
        let cal = Calendar.current
        let now = Date()
        var entries: [CompanionEntry] = [
            CompanionEntry(date: now, display: resolveCompanion(at: now, phase: .current))
        ]
        if let eightPM = cal.date(bySettingHour: 20, minute: 0, second: 0, of: now),
           eightPM > now {
            entries.append(CompanionEntry(date: eightPM,
                display: resolveCompanion(at: eightPM, phase: .eveningAtRisk)))
        }
        let nextMidnight = cal.startOfDay(for: cal.date(byAdding: .day, value: 1, to: now)!)
        entries.append(CompanionEntry(date: nextMidnight,
            display: resolveCompanion(at: nextMidnight, phase: .nextDay)))
        completion(Timeline(entries: entries, policy: .after(nextMidnight)))
    }
}

// MARK: - Views

private func companionDeepLink() -> URL? {
    URL(string: "sakina://widget/muhasabah?homeWidget")
}

private struct StreakBadge: View {
    let display: CompanionDisplay
    var body: some View {
        if display.loggedOut || display.streak <= 0 {
            Text("Begin your streak")
                .font(.custom("Outfit", size: 12)).fontWeight(.semibold)
                .foregroundColor(CPalette.goldInk)
        } else {
            Label("\(display.streak)", systemImage: "flame.fill")
                .font(.custom("Outfit", size: 13)).fontWeight(.bold)
                .foregroundColor(display.checkedIn ? CPalette.emerald : CPalette.goldInk)
                .padding(.horizontal, 9).padding(.vertical, 4)
                .background((display.checkedIn ? CPalette.emerald : CPalette.amber).opacity(0.14))
                .clipShape(Capsule())
        }
    }
}

private struct CompanionSmallView: View {
    let display: CompanionDisplay
    var body: some View {
        VStack(spacing: 6) {
            if let img = companionImage(skinId: display.skin,
                                        brightness: display.brightness) {
                img.resizable().scaledToFit().frame(maxHeight: 92)
            } else {
                Image(systemName: "flame.fill").font(.system(size: 40))
                    .foregroundColor(CPalette.amber)
            }
            StreakBadge(display: display)
            Text(shortLabel(display) == "Reflect" ? "Reflect today" : statusLine(display))
                .font(.custom("Outfit", size: 10.5))
                .foregroundColor(CPalette.ink.opacity(0.7))
                .lineLimit(1).minimumScaleFactor(0.7)
        }
        .padding(12)
        .widgetURL(companionDeepLink())
    }
}

private struct CompanionMediumView: View {
    let display: CompanionDisplay
    var body: some View {
        HStack(spacing: 16) {
            if let img = companionImage(skinId: display.skin,
                                        brightness: display.brightness) {
                img.resizable().scaledToFit().frame(maxWidth: 118, maxHeight: 118)
            } else {
                Image(systemName: "flame.fill").font(.system(size: 48))
                    .foregroundColor(CPalette.amber)
            }
            VStack(alignment: .leading, spacing: 6) {
                Text(display.checkedIn ? "\(display.streak)-day streak"
                        : (display.streak > 0 ? "\(display.streak)-day streak" : "Your muḥāsabah"))
                    .font(.custom("Outfit", size: 17)).fontWeight(.bold)
                    .foregroundColor(CPalette.ink)
                    .lineLimit(1).minimumScaleFactor(0.6)
                Text(statusLine(display))
                    .font(.custom("Outfit", size: 13)).fontWeight(.medium)
                    .foregroundColor(CPalette.ink.opacity(0.72))
                    .lineLimit(2).minimumScaleFactor(0.7)
                Spacer(minLength: 2)
                Link(destination: companionDeepLink() ?? URL(string: "sakina://widget/muhasabah")!) {
                    Label(display.checkedIn ? "Open" : "Reflect",
                          systemImage: "moon.stars.fill")
                        .font(.custom("Outfit", size: 12)).fontWeight(.semibold)
                        .foregroundColor(.white)
                        .padding(.horizontal, 12).padding(.vertical, 6)
                        .background(CPalette.emerald).clipShape(Capsule())
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)
        }
        .padding(16)
        .widgetURL(companionDeepLink())
    }
}

/// Lock Screen (OS-monochrome-tinted): a colored lantern would become a gray
/// blob, so the accessory pairs a TINTABLE SF Symbol (renders cleanly in the
/// OS accent group) with concise, non-clipping text. State via icon + words.
private struct CompanionAccessoryView: View {
    let display: CompanionDisplay
    // `flame.fill` when lit (a burning wick), hollow `flame` when waiting.
    private var symbol: String {
        if display.loggedOut || display.streak <= 0 { return "moon.stars" }
        return display.checkedIn ? "flame.fill" : "flame"
    }
    // Short enough to never truncate at accessory width.
    private var title: String {
        if display.loggedOut || display.streak <= 0 { return "Begin your streak" }
        return display.checkedIn ? "Day \(display.streak) · lit" : "Reflect today"
    }
    private var subtitle: String {
        if display.loggedOut { return "Your light is ready" }
        if display.streak <= 0 { return "Tap to begin" }
        if display.checkedIn { return "May Allah keep you steadfast" }
        return display.atRisk ? "Still time tonight" : "Relight your lantern"
    }
    var body: some View {
        HStack(spacing: 6) {
            Image(systemName: symbol)
                .font(.title3)
                .widgetAccentable() // tint into the OS accent group, not gray
            VStack(alignment: .leading, spacing: 1) {
                Text(title).font(.headline).fontWeight(.semibold)
                    .lineLimit(1).minimumScaleFactor(0.7)
                Text(subtitle).font(.caption)
                    .foregroundStyle(.secondary)
                    .lineLimit(1).minimumScaleFactor(0.7)
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .widgetURL(companionDeepLink())
    }
}

private struct CompanionEntryView: View {
    @Environment(\.widgetFamily) private var family
    let entry: CompanionEntry
    var body: some View {
        switch family {
        case .systemSmall:
            container { CompanionSmallView(display: entry.display) }
        case .accessoryRectangular:
            accessoryContainer { CompanionAccessoryView(display: entry.display) }
        default:
            container { CompanionMediumView(display: entry.display) }
        }
    }
    @ViewBuilder private func accessoryContainer<Content: View>(@ViewBuilder _ content: () -> Content) -> some View {
        if #available(iOS 17.0, *) { content().containerBackground(.clear, for: .widget) }
        else { content() }
    }
    @ViewBuilder private func container<Content: View>(@ViewBuilder _ content: () -> Content) -> some View {
        if #available(iOS 17.0, *) { content().containerBackground(CPalette.cream, for: .widget) }
        else { content().background(CPalette.cream) }
    }
}

struct SakinaCompanionWidget: Widget {
    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kCompanionKind, provider: CompanionProvider()) { entry in
            CompanionEntryView(entry: entry)
        }
        .configurationDisplayName("Your Lantern")
        .description("A living lantern whose light grows with your muḥāsabah streak.")
        .supportedFamilies([.systemSmall, .systemMedium, .accessoryRectangular])
    }
}
