import 'dart:convert';

import 'package:home_widget/home_widget.dart';
import 'package:sakina/core/constants/allah_names.dart';
import 'package:sakina/features/streaks/models/companion_state.dart';
import 'package:sakina/services/location_service.dart';

/// App Group container shared between the Flutter app and the iOS WidgetKit
/// extension. MUST match the App Group capability added to BOTH the Runner and
/// the widget-extension targets in Xcode. See §10.8 of the widget design spec.
const String kWidgetAppGroupId = 'group.com.sakina.app.widget';

/// The `kind` of the iOS widget (WidgetKit `IntentConfiguration`/`Widget`) and
/// the Android provider name. Passed to [HomeWidget.updateWidget].
const String kWidgetName = 'SakinaWidget';

/// The `kind` of the companion (lantern) widget. A THIRD widget in
/// `SakinaWidgetBundle` that reads the SAME [kWidgetPayloadKey] blob and renders
/// the pre-rendered lantern frame for the current streak state. Reloaded
/// alongside [kWidgetName] whenever the streak payload changes.
const String kCompanionWidgetName = 'SakinaCompanionWidget';

/// The single Shared-container key the extension reads. One JSON blob keeps the
/// read atomic on the Swift side.
const String kWidgetPayloadKey = 'sakina_widget_payload';

/// The `kind` of the iOS duʿā-times widget (WidgetKit `Widget`). A SECOND widget
/// in `SakinaWidgetBundle`, distinct from [kWidgetName]. Passed to
/// [HomeWidget.updateWidget] to reload only that widget's timeline (spec §7).
const String kDuaTimesWidgetName = 'SakinaDuaTimesWidget';

/// Shared-container key the duʿā-times extension reads. Holds the JSON-encoded
/// `DuaWindowSchedule` (spec §7). Kept separate from [kWidgetPayloadKey] so the
/// two widgets never contend for the same blob.
const String kDuaTimesPayloadKey = 'sakina_dua_times_payload';

// ── Lantern-skin widget contract (Lane E) ────────────────────────────────────
// The widget extension can't run LanternPainter, so each skin ships as
// pre-rendered PNGs generated by
// `GEN_WIDGET_FRAMES=1 flutter test test/widgets/gen_companion_skin_frames_test.dart`.
// These four declarations are the ONE place the Dart writer, the PNG exporter,
// the on-disk guard test, and the Swift lookup agree.

/// The skin the companion widget falls back to whenever the payload is missing,
/// unreadable, or names a skin this build has no frames for. Mirrors
/// `defaultLanternSkin` in `cosmetics_service.dart` — duplicated deliberately so
/// the widget contract never depends on the economy layer, and pinned equal by
/// `test/services/widget_lantern_frame_contract_test.dart`.
const String kDefaultWidgetLanternSkinId = 'classic_gold';

/// The brightness states the companion widget can actually reach.
/// [CompanionBrightness.dormant] is deliberately absent: the Swift
/// `resolveCompanion` maps streak <= 0 to `endowedDim` and never emits dormant,
/// so a per-skin dormant frame would add ~300 KB × 9 for a state no widget can
/// ever display.
const List<CompanionBrightness> kWidgetCompanionBrightnesses =
    <CompanionBrightness>[
  CompanionBrightness.endowedDim,
  CompanionBrightness.pendingUnlit,
  CompanionBrightness.atRiskUnlit,
  CompanionBrightness.dim,
  CompanionBrightness.glowing,
  CompanionBrightness.fullyLit,
];

/// Skins whose PNG frames are bundled in THIS build of the widget extension.
///
/// Deliberately a hand-maintained literal, NOT derived from `LanternSkin.all`:
/// adding a skin to the code catalog (or the server `cosmetic_catalog`) must NOT
/// make it widget-eligible until someone exports and commits its frames. That
/// asymmetry is what prevents a server-side catalog change from producing a
/// blank widget on already-installed builds — an equipped skin that isn't in
/// this set is silently rendered as [kDefaultWidgetLanternSkinId].
const Set<String> kWidgetBundledSkinIds = <String>{
  // EVERY skin the catalog actually sells. Nothing a user can own falls back on
  // their home screen — not an earned recolor, and not the premium-exclusive.
  //
  // History: Lane E Task 7 measured all NINE client skins at 4,349,953 B
  // (4.15 MiB) against the 4.0 MB gate and fell back to a curated four. That
  // trim was blunt in two ways. First, the ninth skin (`ramadan_gold`) is not
  // seeded in `cosmetic_catalog`, so no user can ever equip it — bundling
  // frames for it was pure waste, and dropping ONLY it brings the set to
  // ~3.9 MB, inside the gate. Second, the four it kept were the default plus
  // the three a-la-carte skins, which left `ramadan_royal` — the rotating
  // SUBSCRIBER-exclusive, i.e. the one thing a monthly payer gets — as the sole
  // paid skin absent from the widget.
  //
  // Bundling `ramadan_royal` is only safe because `resolveWidgetLanternSkin`
  // now routes through the shared `renderableSkinId` (commit c3de10a): a lapsed
  // subscriber resolves to classic_gold. Before that fix this set was the ONLY
  // thing preventing a lapsed subscriber's widget from showing the perk
  // indefinitely — protection by luck rather than by design.
  //
  // Excluded deliberately: `ramadan_gold` (absent from cosmetic_catalog =
  // unobtainable). If it is ever seeded, add it here AND regenerate frames with
  // `GEN_WIDGET_FRAMES=1`, then re-check the total against the 4.0 MB gate.
  'classic_gold',
  'moonlit_silver',
  'emerald_jade',
  'rose_quartz',
  'obsidian_gold',
  'masjid_brass',
  'crystal_star',
  'ramadan_royal',
};

/// File name of the exported frame for [skinId] at [brightness]. Mirrored by
/// `companionAssetCandidates` in `ios/SakinaWidget/CompanionSkinResolver.swift`.
String companionWidgetFrameAsset(
        String skinId, CompanionBrightness brightness) =>
    'companion_${skinId}_${brightness.name}.png';

/// Widget-eligibility filter. Applied by the single payload writer, so a skin id
/// this build cannot render never reaches the shared container at all.
String widgetEligibleSkinId(String equippedSkinId) =>
    kWidgetBundledSkinIds.contains(equippedSkinId)
        ? equippedSkinId
        : kDefaultWidgetLanternSkinId;

/// Immutable, JSON-serialisable widget payload. Mirrors §4.3 of the spec.
///
/// The extension ONLY trusts [nameKey]/[anchor] when [checkedInToday] is true
/// AND [updatedAtIso] is from the current local day; otherwise it computes the
/// daily Name from its bundled catalog. [streak] is always shown from the last
/// written value.
class WidgetNamePayload {
  const WidgetNamePayload({
    required this.mode,
    required this.nameKey,
    required this.name,
    required this.nameEnglish,
    required this.arabic,
    required this.transliteration,
    required this.anchor,
    required this.checkedInToday,
    required this.streak,
    required this.updatedAtIso,
    required this.lanternSkin,
  });

  /// `personalized` = show [nameKey]; `daily` = extension picks the daily Name.
  final String mode;
  final String nameKey;
  final String name;
  final String nameEnglish;
  final String arabic;
  final String transliteration;
  final String anchor;
  final bool checkedInToday;
  final int streak;
  final String updatedAtIso;

  /// The equipped lantern skin id, already filtered through
  /// [widgetEligibleSkinId] by the writer — the companion widget loads
  /// `companion_<lanternSkin>_<brightness>.png`. Additive key: widget builds
  /// older than Lane E decode the blob fine and ignore it.
  final String lanternSkin;

  Map<String, dynamic> toJson() => {
        'mode': mode,
        'name_key': nameKey,
        'name': name,
        'name_english': nameEnglish,
        'arabic': arabic,
        'transliteration': transliteration,
        'anchor': anchor,
        'checked_in_today': checkedInToday,
        'streak': streak,
        'updated_at': updatedAtIso,
        'lantern_skin': lanternSkin,
      };

  /// Same payload with a new skin + timestamp. Lets [WidgetDataService] re-push
  /// on equip without a read-modify-write (the [HomeWidgetClient] seam has no
  /// read).
  WidgetNamePayload withLanternSkin(String skinId, String newUpdatedAtIso) =>
      WidgetNamePayload(
        mode: mode,
        nameKey: nameKey,
        name: name,
        nameEnglish: nameEnglish,
        arabic: arabic,
        transliteration: transliteration,
        anchor: anchor,
        checkedInToday: checkedInToday,
        streak: streak,
        updatedAtIso: newUpdatedAtIso,
        lanternSkin: skinId,
      );

  String encode() => jsonEncode(toJson());
}

/// Thin seam over the `home_widget` static API so [WidgetDataService] is unit
/// testable without the platform channel. The default delegates to the plugin.
abstract class HomeWidgetClient {
  Future<void> setAppGroupId(String id);
  Future<void> saveWidgetData(String key, String? value);
  Future<void> updateWidget({required String name});
}

class _PluginHomeWidgetClient implements HomeWidgetClient {
  const _PluginHomeWidgetClient();

  @override
  Future<void> setAppGroupId(String id) => HomeWidget.setAppGroupId(id);

  @override
  Future<void> saveWidgetData(String key, String? value) =>
      HomeWidget.saveWidgetData<String?>(key, value);

  @override
  Future<void> updateWidget({required String name}) =>
      HomeWidget.updateWidget(iOSName: name, name: name);
}

/// Single writer of home-screen widget state.
///
/// Call [syncWidget] from the data-sync completion (see §10.4) rather than
/// scattering calls across feature sites. Call [clearWidget] on sign-out and
/// account deletion so a second user on the device never sees the first user's
/// streak or Name (§10.5).
class WidgetDataService {
  WidgetDataService({
    HomeWidgetClient? client,
    DateTime Function()? clock,
    LocationService? locationService,
  })  : _client = client ?? const _PluginHomeWidgetClient(),
        _clock = clock ?? DateTime.now,
        _location = locationService ?? LocationService();

  final HomeWidgetClient _client;
  final DateTime Function() _clock;
  final LocationService _location;

  /// Last serialized payload written this process — the perf guard (§10.4):
  /// skip [HomeWidget.updateWidget] when nothing changed.
  String? _lastWritten;

  /// Last duʿā-times schedule JSON written this process — the same perf guard
  /// as [_lastWritten], but for the duʿā-times widget. Skips the save +
  /// WidgetKit reload when the schedule is byte-identical (spec §7: the
  /// ~40-70/day reload budget is easy to burn on every foreground rebuild).
  String? _lastDuaTimesWritten;

  /// Last equipped lantern skin this process knows about, already filtered to a
  /// bundled id. Remembered so an equip (which knows the skin but not the Name)
  /// and a sync (which knows the Name but may not pass a skin) can't clobber
  /// each other.
  String _equippedSkin = kDefaultWidgetLanternSkinId;

  /// The last payload written this process. Kept so [setEquippedLanternSkin]
  /// can re-push with only the skin changed — the [HomeWidgetClient] seam is
  /// write-only, so there is nothing to read back.
  WidgetNamePayload? _lastPayload;

  /// Register the App Group. Call once from `main()` before `runApp`.
  Future<void> initialize() async {
    await _client.setAppGroupId(kWidgetAppGroupId);
  }

  /// Compose the payload for [name] and push it to the widget. Only reloads the
  /// timeline when the serialized payload actually changed.
  ///
  /// [personalized] true means [name] is the Name the user received in today's
  /// muḥāsabah.
  ///
  /// [name] is **null when today's Name has not been revealed yet** (W4 Wave 6).
  /// That emits `mode: 'awaiting'` with the Name fields blank, and the extension
  /// renders the invitation instead of naming a Name. It is a positive
  /// statement, not missing data: the widget used to advertise a day-of-year
  /// rotation that had nothing to do with the reveal, which the loop now makes
  /// into a broken promise rather than a harmless placeholder.
  ///
  /// The blank fields are deliberate — a Name left in the payload "just in
  /// case" is a Name some future reader will render. Older installed widget
  /// builds degrade safely: they only ever read these fields when
  /// `mode == 'personalized'`, so an unrecognised `'awaiting'` falls through to
  /// their own catalog rotation, i.e. exactly today's behaviour.
  ///
  /// [lanternSkinId] is the user's equipped skin; pass null to keep the last
  /// known one (an equip may have set it since the previous sync).
  Future<void> syncWidget({
    required AllahName? name,
    required String anchor,
    required int streak,
    required bool checkedInToday,
    required bool personalized,
    String? lanternSkinId,
  }) async {
    if (lanternSkinId != null) {
      _equippedSkin = widgetEligibleSkinId(lanternSkinId);
    }
    final payload = WidgetNamePayload(
      mode: personalized
          ? 'personalized'
          : (name == null ? 'awaiting' : 'daily'),
      nameKey: name == null ? '' : widgetNameKeyFor(name),
      name: name?.transliteration ?? '',
      nameEnglish: name?.english ?? '',
      arabic: name?.arabic ?? '',
      transliteration: name?.transliteration ?? '',
      anchor: anchor,
      checkedInToday: checkedInToday,
      streak: streak,
      // UTC + trailing 'Z' so the Swift ISO8601DateFormatter can parse it; the
      // extension compares it against the current LOCAL day (§10.7).
      updatedAtIso: _clock().toUtc().toIso8601String(),
      lanternSkin: _equippedSkin,
    );
    _lastPayload = payload;
    await _write(payload.encode());
  }

  /// Push a precomputed duʿā-window schedule (already JSON-encoded by the engine
  /// per the §7 serialization contract) to the duʿā-times widget, then reload its
  /// timeline. The extension decodes it from the App Group; when it is missing,
  /// stale, or the travel guard trips, the widget falls back to its bundled
  /// calendar (spec §9/§10).
  ///
  /// Signature is a fixed contract — the `dua_window_provider` calls this exact
  /// shape. Do not change it.
  Future<void> saveDuaTimesSchedule(String scheduleJson) async {
    // Perf guard (spec §7): the provider rebuilds + pushes on every foreground,
    // date-rollover, and tick-driven rebuild. A WidgetKit reload per push burns
    // the ~40-70/day budget fast, so skip the save + reload when the schedule
    // is byte-identical to the last one written this process.
    if (scheduleJson == _lastDuaTimesWritten) return;
    _lastDuaTimesWritten = scheduleJson;
    await _client.saveWidgetData(kDuaTimesPayloadKey, scheduleJson);
    await _client.updateWidget(name: kDuaTimesWidgetName);
  }

  /// Push the newly equipped lantern skin to the companion widget immediately.
  ///
  /// Called by `equipCosmetic` on a successful `lantern_skin` equip so the
  /// home-screen lantern changes while the user is still looking at the
  /// wardrobe, instead of waiting for the next sync. Unbundled ids are filtered
  /// to [kDefaultWidgetLanternSkinId] — the widget can only render frames this
  /// build actually ships.
  ///
  /// Before the first [syncWidget] of the process there is no payload to patch;
  /// the skin is remembered and the next sync carries it.
  Future<void> setEquippedLanternSkin(String skinId) async {
    final eligible = widgetEligibleSkinId(skinId);
    if (eligible == _equippedSkin) return;
    _equippedSkin = eligible;

    final last = _lastPayload;
    if (last == null) return;
    final patched =
        last.withLanternSkin(eligible, _clock().toUtc().toIso8601String());
    _lastPayload = patched;
    await _write(patched.encode());
  }

  /// Wipe personalized state from the shared container and revert the widgets to
  /// their daily/calendar fallbacks. MUST run on sign-out and account deletion.
  ///
  /// Also nulls [kDuaTimesPayloadKey] so a second user on the device never
  /// inherits the first user's location-derived schedule — which would leak
  /// their approximate home location (spec §7 privacy fix).
  Future<void> clearWidget() async {
    await _client.saveWidgetData(kWidgetPayloadKey, null);
    await _client.saveWidgetData(kDuaTimesPayloadKey, null);
    // Also wipe the raw coarse lat/lon cache: nulling the derived schedule isn't
    // enough — the next user's rebuild would re-derive precise times from the
    // first user's cached location (spec §7 privacy fix).
    await _location.clearCache();
    _lastWritten = null;
    _lastDuaTimesWritten = null;
    // A second user on this device must not inherit the first user's lantern.
    _equippedSkin = kDefaultWidgetLanternSkinId;
    _lastPayload = null;
    await _client.updateWidget(name: kWidgetName);
    await _client.updateWidget(name: kCompanionWidgetName);
    await _client.updateWidget(name: kDuaTimesWidgetName);
  }

  Future<void> _write(String encoded) async {
    // `updated_at` changes every call, so compare on the semantic payload minus
    // the timestamp — otherwise the guard never fires.
    final comparable = _stripTimestamp(encoded);
    if (comparable == _lastWritten) return;
    _lastWritten = comparable;
    await _client.saveWidgetData(kWidgetPayloadKey, encoded);
    await _client.updateWidget(name: kWidgetName);
    // The companion widget reads the same blob — reload its timeline too so its
    // lantern brightness tracks the streak.
    await _client.updateWidget(name: kCompanionWidgetName);
  }

  String _stripTimestamp(String encoded) {
    final map = jsonDecode(encoded) as Map<String, dynamic>;
    map.remove('updated_at');
    return jsonEncode(map);
  }
}

/// Global instance, matching the codebase's `supabaseSyncService` pattern.
final WidgetDataService widgetDataService = WidgetDataService();
